kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stakater-tekton-builder
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineresources
      - pipelineruns
    verbs:
      - get
      - create
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
      - triggers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workshop-event-listener
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - clusterinterceptors
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workshop-event-listener
subjects:
  - kind: ServiceAccount
    name: workshop-event-listener
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: Role
  name: workshop-event-listener
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop-event-listener
subjects:
  - kind: ServiceAccount
    name: workshop-event-listener
    namespace: user40
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole
  name: workshop-event-listener
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-event-listener