
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: workshop-pipeline
spec:
  params: 
  - name: name
    type: string
  tasks:
  - name: first-task
    taskRef:
      name: task1
  - name: second-task
    taskRef:
      name: task2
    params: 
       - name: name
         value: $(params.name)
    runAfter:
      - first-task