apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  steps:
  - name: task-two-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'echo first step']
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task2
spec:
  params:
  - name: name
  steps:
    - name: echo-hello-world
      image: docker.io/library/busybox
      command:
       - /bin/sh
      args:
        - -c
        - "echo Hello $(params.name)"